import type { Metadata, Viewport } from 'next';
import './globals.css';
import SiteHeader from '@/components/SiteHeader';
import { ProvProvider } from '@/components/Prov';

export const metadata: Metadata = {
  title: { default: 'Country Value Retention: Cyprus', template: '%s · Country Value Retention' },
  description:
    'Of the value generated in Cyprus, where does it ultimately accrue? Official primary income paid abroad versus income generated by Cypriot production that accrues to non-residents.',
};

export const viewport: Viewport = { width: 'device-width', initialScale: 1 };

const themeInit = `try{var t=localStorage.getItem('theme');if(t)document.documentElement.dataset.theme=t}catch(e){}`;

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script dangerouslySetInnerHTML={{ __html: themeInit }} />
      </head>
      <body>
        <ProvProvider>
          <SiteHeader />
          <main className="wrap">{children}</main>
          <footer className="site">
            <div className="wrap">
              Research dashboard by Diomides Mavroyiannis (Milestone Institute). Every number carries its status,
              confidence, source and method: hover or tap it. Metrics are shown side by side and never added
              together: they are measured on different bases.
            </div>
          </footer>
        </ProvProvider>
      </body>
    </html>
  );
}
