'use client';
import type { Headline } from '@/lib/types';
import { METRICS } from '@/lib/concepts';
import { eurM, pct } from '@/lib/format';
import Link from 'next/link';
import LineChart from './LineChart';
import { Num } from './Prov';

/** The key message: official outflow (with SPE pass-through) vs income generated by Cypriot production that accrues abroad. */
export default function Contrast({ headline, year }: { headline: Headline; year: number }) {
  const s = headline.series;
  const h = s.find((r) => r.year === year)!;
  const off = s.map((r) => r.official_primary_income_outflow_to_gdp);
  const fvl = s.map((r) => r.foreign_value_leakage);
  const range = (a: number[]) => `${pct(Math.min(...a), 0)}–${pct(Math.max(...a), 0)}`;
  const O = METRICS.official_primary_income_outflow_to_gdp;
  const F = METRICS.foreign_value_leakage;
  const max = Math.max(h.official_primary_income_outflow_to_gdp, h.foreign_value_leakage);
  return (
    <section className="card">
      <h2>Two different questions, two very different numbers</h2>
      <p className="explain">
        Official statistics record primary income paid abroad equal to <strong>{range(off)} of GDP</strong> ({s[0].year}–
        {s[s.length - 1].year}). Most of it only passes through Cypriot special purpose entities (SPEs): holding
        companies that receive dividends from abroad and pay them on to foreign owners. Income generated by Cypriot
        production that accrues abroad is <strong>{range(fvl)} of GDP</strong>. The two are shown side by side; they are
        not added or netted.
      </p>
      <h3>
        {year}: share of GDP
      </h3>
      <div className="barlist wrapnames" style={{ marginBottom: '1rem' }}>
        <div className="bl-name">{O.label}</div>
        <div className="bl-bar">
          <span className="bl-fill" style={{ width: `${(h.official_primary_income_outflow_to_gdp / max) * 70}%`, background: 'var(--s2)' }} />
          <span className="bl-val">
            <Num prov={O.prov} title={`${O.label}, ${year}. ${O.question}`}>
              {pct(h.official_primary_income_outflow_to_gdp)}
            </Num>
          </span>
        </div>
        <div className="bl-name">Income from Cypriot production accruing abroad</div>
        <div className="bl-bar">
          <span className="bl-fill" style={{ width: `${Math.max(0.5, (h.foreign_value_leakage / max) * 70)}%`, background: 'var(--s1)' }} />
          <span className="bl-val">
            <Num prov={F.prov} title={`${F.label}, ${year}. ${F.question}`}>
              {pct(h.foreign_value_leakage)}
            </Num>{' '}
            <span className="muted small">
              (<Num prov={F.prov} title={`${F.label} in EUR, ${year}`}>{eurM(h.foreign_value_leakage_eur_m)}</Num>)
            </span>
          </span>
        </div>
      </div>
      <h3>Over time, share of GDP</h3>
      <LineChart
        ariaLabel="Official primary income paid abroad versus foreign value leakage, share of GDP by year"
        fmt={(v) => pct(v, 0)}
        highlightX={year}
        series={[
          { key: 'off', label: 'Official primary income paid abroad', short: 'Official outflow', color: 'var(--s2)', prov: O.prov, points: s.map((r) => ({ x: r.year, y: r.official_primary_income_outflow_to_gdp })) },
          { key: 'fvl', label: 'Income from Cypriot production accruing abroad (FVL)', short: 'Model: FVL', color: 'var(--s1)', prov: F.prov, points: s.map((r) => ({ x: r.year, y: r.foreign_value_leakage })) },
        ]}
      />
      <p className="small muted">
        Why GNI is not the answer: GNI adds income Cypriot residents earn abroad, which is value generated elsewhere,
        and the official outflow counts SPE pass-through that was never generated by Cypriot production. See{' '}
        <Link href="/methodology/">methodology</Link>.
      </p>
    </section>
  );
}
