"""Frame A estimator: who receives the value added generated in Cyprus in year t.

Builds an ``IncomeAccount`` (national accounts, 64 industries) and its outflow
table from official sources, one mechanism at a time.  Every outflow row
carries status/methodology/source so the tensor stays auditable.  Parameters
that are not observed (foreign equity share theta, corporate tax rate tau) are
explicit arguments so sensitivity analysis can vary them.

Mechanisms (see docs/methodology.md for the full rationale):

  M1 compensation_nonresident   CYSTAT S2 D1 (paid by CY) x BoP partner shares; industry ∝ D1_k
  M2 fdi_income                 FATS operating surplus of foreign-controlled firms, by section and
                                ultimate controlling country, net of depreciation and corporate tax,
                                x theta.  Before 2021 FATS excludes finance: foreign-owned banks enter
                                via BoP S122 FDI equity income instead.
  M3 other_investment_income    BoP interest/dividends paid by non-SPE sectors on portfolio and other
     portfolio_income           investment: S1V (firms, households) gross; S122 banks net of receipts.
     public_debt_interest       S13 general government, financed from the tax pool.
  M4 taxes_to_eu_institutions   CYSTAT S2 D2 received by the rest of the world.

Excluded by design: income paid by financial corporations other than MFIs
(S12M) — Cyprus's SPEs and captive financial units — which is pass-through
income not generated by Cypriot production.  It is reported separately.
"""

from __future__ import annotations

import glob
from dataclasses import dataclass, replace
from functools import lru_cache
from pathlib import Path

import pandas as pd

from ..accounts import PRODUCT_TAXES, IncomeAccount
from .industries import canon, cover, divisions, from_nama, section

EUROSTAT = Path("data/raw/eurostat")
CYSTAT = Path("data/interim/cystat")
AGG_PARTNERS = {"CONFIDENTIAL_PARTNERS"}

# Cyprus statutory corporate income tax rate (Income Tax Law 118(I)/2002 as amended):
# 10% to 2012, 12.5% 2013-2025, 15% from 2026.
STATUTORY_CIT = {y: (0.10 if y <= 2012 else 0.125) for y in range(2008, 2026)}


@dataclass(frozen=True)
class Params:
    theta: float | None = None  # non-resident equity share; None = calibrated value (ownership_data.theta_central)
    tax: str = "statutory"  # "statutory" or "none"
    include_ofc: bool = False  # sensitivity: include S12M (SPE-dominated) outflows
    consistent_scope: bool = False  # FATS sections B-N only in every year, banks via BoP -> no 2021 break
    banks_gross: bool = False  # sensitivity: banks' non-FDI interest paid abroad gross, not net of receipts
    bop_upper: bool = False  # sensitivity: foreign-owned profit = max(FATS-based, BoP FDI equity income paid)
    rho_basis: str = "d41_gross"  # interest deducted: "d41_gross" (central), "d41_net", "d41g_gross", "none" (variants)


def _one(pattern: str) -> pd.DataFrame:
    files = sorted(glob.glob(str(EUROSTAT / pattern)))
    if not files:
        raise FileNotFoundError(pattern)
    return pd.concat([pd.read_parquet(f) for f in files], ignore_index=True)


@lru_cache(maxsize=None)
def _nama() -> pd.DataFrame:
    d = _one("nama_10_a64__*.parquet")
    d = d[d.unit == "CP_MEUR"].copy()
    d["TIME_PERIOD"] = d.TIME_PERIOD.astype(int)
    return d


def na_industry(year: int) -> pd.DataFrame:
    """B1G, D1, D29X39, P51C, B2A3N and B2A3G by canonical industry (EUR m)."""
    d = _nama()
    d = d[d.TIME_PERIOD == year].pivot_table(
        index="nace_r2", columns="na_item", values="OBS_VALUE"
    )
    out = pd.DataFrame(index=canon())
    for code in out.index:
        src = {"L68B": None}.get(code, code)
        if code == "L68B":
            row = d.loc["L68"] - d.loc["L68A"]
        else:
            matches = [k for k in d.index if from_nama(k) == src]
            if not matches:
                raise KeyError(f"{year}: industry {code} missing in nama_10_a64")
            row = d.loc[matches[0]]
        out.loc[code, ["B1G", "D1", "D29X39", "P51C", "B2A3N"]] = row[
            ["B1G", "D1", "D29X39", "P51C", "B2A3N"]
        ].values
    out = out.astype(float).fillna(0.0)
    out["B2A3G"] = out["B2A3N"] + out["P51C"]
    total = d.loc["TOTAL", "B1G"]
    if abs(out["B1G"].sum() - total) > 1.0:
        raise AssertionError(
            f"{year}: A64 industries sum to {out['B1G'].sum():.1f}, TOTAL {total:.1f}"
        )
    return out


@lru_cache(maxsize=None)
def _sector() -> pd.DataFrame:
    s = pd.read_parquet(CYSTAT / "sector_accounts.parquet")
    return s.pivot_table(
        index=["reference_year", "sector"], columns="item", values="value"
    )


@lru_cache(maxsize=None)
def _nasa() -> pd.DataFrame:
    d = _one("nasa_10_nf_tr__geo-CY*.parquet")
    d = d[d.unit == "CP_MEUR"].copy()
    d["TIME_PERIOD"] = d.TIME_PERIOD.astype(int)
    return d


def _nasa_val(year: int, sector: str, item: str, direct: str = "PAID") -> float:
    d = _nasa()
    x = d[(d.TIME_PERIOD == year) & (d.sector == sector) & (d.na_item == item) & (d.direct == direct)]["OBS_VALUE"].dropna()
    if x.empty:
        raise KeyError(f"nasa_10_nf_tr {sector} {item} {direct} {year} missing")
    return float(x.iloc[0])


def corporate_nos(year: int) -> float:
    """Net operating surplus of non-financial corporations (S11): excludes mixed income, imputed
    rent and finance, whose FATS coverage changes in 2021."""
    return _nasa_val(year, "S11", "B2A3G") - _nasa_val(year, "S11", "P51C")


def corporate_ratios(year: int, rho_basis: str = "d41_gross") -> dict[str, float]:
    """Depreciation and interest per euro of gross operating surplus of non-financial corporations.

    Corporate-sector ratios (not industry ones) are used because industry B2A3G includes the
    mixed income of the self-employed, which foreign-controlled firms do not have.

    Interest (rho), central choice: S11 interest paid (D41, after the FISIM adjustment, gross),
    per euro of S11 GOS - the interest the average non-financial firm owes on its surplus.
    Interest *received* is not netted: receipts from abroad are not value generated in Cyprus
    and netting would credit them to foreign owners.  Variants: "d41_net" (paid - received),
    "d41g_gross" (actual interest before FISIM: c + rho >= 0.996 in 2010-2015, i.e. (almost) no
    profit; 11-29% of surplus left in 2016-2020; close to the central ratio from 2021), "none".  Interest is deducted only for non-financial industries.

    intra_group_share: BoP FDI debt interest paid by S1V / S11 D41 paid: the share of firms'
    interest that goes to their own foreign parents or affiliates (includes pass-through, so an
    upper bound).
    """
    b11, b12 = _nasa_val(year, "S11", "B2A3G"), _nasa_val(year, "S12", "B2A3G")
    d41 = _nasa_val(year, "S11", "D41")
    if rho_basis == "d41_gross":
        rho = d41 / b11
    elif rho_basis == "d41_net":
        rho = (d41 - _nasa_val(year, "S11", "D41", "RECV")) / b11
    elif rho_basis == "d41g_gross":
        rho = _nasa_val(year, "S11", "D41G") / b11
    elif rho_basis == "none":
        rho = 0.0
    else:
        raise ValueError(rho_basis)
    debt, _ = _bop(year, "S1V", "D41__D__FLA", "DEB")
    return {
        "cfc_nonfin": _nasa_val(year, "S11", "P51C") / b11,
        "interest_nonfin": max(rho, 0.0),
        "intra_group_share": min(debt / d41, 1.0) if pd.notna(debt) and d41 > 0 else 0.0,
        "cfc_fin": _nasa_val(year, "S12", "P51C") / b12,
        "employer_ssc_share": _nasa_val(year, "S1", "D12") / _nasa_val(year, "S1", "D1"),
        "household_interest_share": _nasa_val(year, "S14_S15", "D41") / (_nasa_val(year, "S14_S15", "D41") + d41),
    }


def gdp(year: int) -> float:
    return float(_sector().loc[(year, "S1"), "B1GQ"])


def _row(mech, partner, industry, value, status, method, source, conf):
    return {
        "mechanism": mech,
        "partner": partner,
        "industry": industry,
        "value": float(value),
        "status": status,
        "methodology": method,
        "source": source,
        "confidence_level": conf,
    }


def _alloc(total: float, weights: pd.Series) -> pd.Series:
    w = weights.clip(lower=0)
    return total * w / w.sum() if w.sum() > 0 else w * 0


def _partner_shares(values: pd.Series, total: float) -> pd.Series:
    """Published country values; the unpublished remainder goes to an explicit bucket."""
    v = values.dropna()
    v = v[v > 0]
    rest = total - v.sum()
    if rest < -1e-6 * max(total, 1):
        v = (
            v * total / v.sum()
        )  # published parts exceed total (rounding/revisions): rescale
        rest = 0.0
    out = pd.concat([v, pd.Series({"CONFIDENTIAL_PARTNERS": max(rest, 0.0)})])
    return out[out > 0] / total if total > 0 else out * 0


# Two-letter codes in Eurostat's PARTNER list that are aggregates, not economies (checked
# against the codelist 2026-09-24): counting them beside their members would double count.
TWO_LETTER_AGGREGATES = {"EU", "EA", "FZ"}  # EU, euro area, Franc Zone


def _is_country(code: str) -> bool:
    return len(code) == 2 and code.isalpha() and code not in TWO_LETTER_AGGREGATES


# ---------- M1 compensation of non-resident employees ----------
def m1_labour(year: int, na: pd.DataFrame) -> tuple[list[dict], dict]:
    """Compensation of non-resident employees net of Cypriot employer social contributions.

    D1 includes employers' social contributions paid to Cypriot social insurance; like the
    corporate tax deducted from foreign owners, that part accrues to Cyprus.  Taxes and
    contributions withheld from the workers themselves are not observed (BoP D5/D61 credits are
    zero) and are not deducted.
    """
    gross = float(_sector().loc[(year, "S2"), "D1REC"])  # received by RoW = paid by CY
    ssc = corporate_ratios(year)["employer_ssc_share"]
    total = gross * (1 - ssc)
    r = _one("bop_rem6__*.parquet")
    r = r[(r.bop_item == "D1") & (r.stk_flow == "DEB") & (r.TIME_PERIOD.astype(int) == year)]
    by = r[r.partner.map(_is_country) & (r.partner != "CY")].set_index("partner")["OBS_VALUE"]
    shares = _partner_shares(by, gross)
    rows = []
    ind = _alloc(1.0, na["D1"])
    for p, s in shares.items():
        for k, w in ind[ind > 0].items():
            rows.append(
                _row(
                    "compensation_nonresident",
                    p,
                    k,
                    total * s * w,
                    "estimated",
                    f"S2 D1 (observed) x (1 - employer social contributions share {ssc:.3f}) x BoP bop_rem6 partner share (unpublished partners pooled) x industry share of D1",
                    "CYSTAT 0630030E; Eurostat bop_rem6; nasa_10_nf_tr",
                    "medium" if p != "CONFIDENTIAL_PARTNERS" else "low",
                )
            )
    return rows, {"labour_gross": gross, "labour_net": total, "employer_ssc_share": ssc}


# ---------- M2 foreign-controlled operating surplus (FATS) ----------
_FATS_AGG = {
    "WORLD",
    "DOM",
    "WRL_REST",
    "WRL_X_REP",
    "CONTROL",
    "INT_EU27_2020",
    "EXT_EU27_2020",
}


def fats_foreign_gos(year: int, consistent_scope: bool = False) -> dict:
    """Foreign-controlled GOS by section, UCI country totals, and the published section x country cells."""
    if year >= 2021:
        d = _one("fats_activ__*.parquet")
        d = d[d.TIME_PERIOD.astype(int) == year]
        g = d[d.indic_sbs == "GOS_MEUR"].pivot_table(index="nace_r2", columns="c_ctrl", values="OBS_VALUE")
        total_code, scope, foreign = "B-S_X_O_S94", "business economy B-S excl. O and S94, incl. finance K", "WRL_REST"
    else:
        d = _one("fats_g1a_08__*.parquet")
        d = d[d.TIME_PERIOD.astype(int) == year]
        p = d[d.indic_sb.isin(["V12150", "V13310"])].pivot_table(index=["nace_r2", "c_ctrl"], columns="indic_sb", values="OBS_VALUE")
        g = (p["V12150"] - p["V13310"]).unstack("c_ctrl")
        total_code, scope, foreign = "B-N_S95_X_K", "business economy B-N and S95, excl. finance K", "WRL_X_REP"
    # Only sections inside the dataset's scope may receive the remainder of the published total:
    # fats_g1a_08 covers B-N (and S95) excluding K; fats_activ covers B-S excluding O and S94.
    in_scope = set("BCDEFGHIJKLMNPQR") if year >= 2021 else set("BCDEFGHIJLMN")
    sections = [s for s in g.index if len(s) == 1 and s in in_scope]
    tot = float(g.loc[total_code, foreign])
    sec = g.loc[sections, foreign].copy()
    known = sec.dropna()
    missing = sec.index[sec.isna()]
    if len(missing):
        # confidential sections: remainder of the published total, split by all-owner GOS
        rest = max(tot - known.clip(lower=0).sum(), 0.0)
        allg = g.loc[missing, "WORLD"].fillna(0).clip(lower=0)
        sec.loc[missing] = rest * allg / allg.sum() if allg.sum() > 0 else rest / len(missing)
    # Suppressed economies stay in CONFIDENTIAL_PARTNERS: imputing them into named countries would
    # publish model values for cells the statistical office suppressed (residual disclosure).
    ctry = _uci_countries(g.loc[total_code])
    col_totals = _partner_shares(ctry, tot) * tot
    sec = sec.fillna(0.0)
    cells = g.loc[sections, [c for c in col_totals.index if c in g.columns]]
    if consistent_scope and year >= 2021:
        sec = sec.drop(index=[s for s in "KPQR" if s in sec.index])
        scope += " [consistent scope: sections B-N only; banks via BoP]"
    return {"sections": sec, "col_totals": col_totals, "cells": cells, "scope": scope, "codes": g[foreign], "total": tot}


def section_country_shares(sections: pd.Series, col_totals: pd.Series, cells: pd.DataFrame, iters: int = 500) -> pd.DataFrame:
    """Section x UCI-economy shares: published cells fixed, the rest fitted to both margins (IPF).

    Row margins are the section totals, column margins the published economy-wide UCI totals plus the
    CONFIDENTIAL_PARTNERS remainder.  A published cell is never
    changed unless the published cells of a row exceed its total (then they are scaled).
    """
    rows = sections.clip(lower=0)
    cols = col_totals.clip(lower=0)
    if rows.sum() <= 0:
        return pd.DataFrame(0.0, index=sections.index, columns=cols.index)
    cols = cols * rows.sum() / cols.sum()
    known = cells.reindex(index=rows.index, columns=cols.index).clip(lower=0)
    fixed = known.notna()
    kv = known.fillna(0.0)
    over = kv.sum(axis=1) > rows
    kv.loc[over] = kv.loc[over].mul(rows[over] / kv.loc[over].sum(axis=1), axis=0)
    free_r = (rows - kv.sum(axis=1)).clip(lower=0)
    free_c = (cols - kv.sum(axis=0)).clip(lower=0)
    m = pd.DataFrame(0.0, index=rows.index, columns=cols.index)
    if free_r.sum() > 0 and free_c.sum() > 0:
        m = pd.DataFrame(free_r.values[:, None] * free_c.values[None, :] / free_c.sum(), index=rows.index, columns=cols.index)
        m = m.where(~fixed, 0.0)
        for _ in range(iters):
            rs = m.sum(axis=1)
            m = m.mul((free_r / rs.where(rs > 0)).fillna(0), axis=0)
            cs = m.sum(axis=0)
            m = m.mul((free_c / cs.where(cs > 0)).fillna(0), axis=1)
        rs = m.sum(axis=1)
        m = m.mul((free_r / rs.where(rs > 0)).fillna(0), axis=0)  # rows exact (section totals are the data)
    full = m + kv
    # a row whose published cells cannot absorb its total (no free cell left): the remainder is
    # unpublished, so it goes to CONFIDENTIAL_PARTNERS, never onto the published cells
    left = (rows - full.sum(axis=1)).clip(lower=0)
    if left.sum() > 1e-9:
        if "CONFIDENTIAL_PARTNERS" not in full:
            full["CONFIDENTIAL_PARTNERS"] = 0.0
        full["CONFIDENTIAL_PARTNERS"] += left
    return full.div(full.sum(axis=1).where(full.sum(axis=1) > 0), axis=0).fillna(0.0)


# Eurostat's OFFSHO aggregate contains these economies, which FATS also lists individually.
OFFSHO_MEMBERS_IN_FATS = {"HK", "LI"}


def _uci_countries(row: pd.Series) -> pd.Series:
    """Individual UCI economies + the offshore-centre aggregate, each counted once."""
    keep = [c for c in row.index if _is_country(c) and c not in OFFSHO_MEMBERS_IN_FATS]
    if "OFFSHO" in row.index:
        keep.append("OFFSHO")
    return row[keep]


def allocate_fats(sec: pd.Series, codes: pd.Series, na: pd.DataFrame) -> tuple[pd.Series, dict[str, str], dict[str, float]]:
    """Foreign-controlled GOS by canonical industry, using the finest published FATS codes.

    Within each section: (a) published codes that exactly cover whole canonical industries,
    and (b) 'virtual' codes summing a complete set of published child divisions (C10+C11+C12
    -> C10-12), finest first, non-overlapping.  The unpublished remainder of the section is
    split over the uncovered industries by gross operating surplus.  Imputed rent (L68A)
    never receives foreign surplus.  Returns (values, code used per industry, losses).
    """
    inds = [k for k in na.index]
    weight = na["B2A3G"].clip(lower=0).copy()
    weight["L68A"] = 0.0
    out = pd.Series(0.0, index=inds)
    used: dict[str, str] = {}
    losses: dict[str, float] = {}
    pub = codes.dropna()
    for s_code, total in sec.items():
        members_s = [k for k in inds if section(k) == s_code]
        cands = []
        for c, v in pub.items():
            if c == s_code or not c.startswith(s_code):
                continue
            mem = cover(c, members_s)
            if mem:
                cands.append((len(mem), c, mem, float(v)))
        for k in members_s:  # virtual codes from complete sets of single divisions
            dk = divisions(k)
            if dk is None or len(dk) < 2:
                continue
            parts = [f"{s_code}{d:02d}" for d in sorted(dk)]
            if all(p in pub.index for p in parts):
                cands.append((1, "+".join(parts), [k], float(pub[parts].sum())))
        cands.sort(key=lambda x: x[0])
        covered: set[str] = set()
        picked = []
        for _, c, mem, v in cands:
            if covered.isdisjoint(mem):
                picked.append((c, mem, v))
                covered.update(mem)
        # Losses in a sub-code are owners' losses, not outflows; clip them so the section total
        # is conserved (the remainder must not grow to offset a negative sub-code).
        assigned = sum(max(v, 0.0) for _, _, v in picked)
        if total > 0 and assigned > total * (1 + 1e-6):
            scale = total / assigned  # published parts exceed the section total (revisions)
            picked = [(c, m_, v * scale) for c, m_, v in picked]
            assigned = total
        residual = total - assigned
        for c, mem, v in picked:
            if v < 0:
                losses[c] = v
                continue
            w = weight[mem]
            share = w / w.sum() if w.sum() > 0 else pd.Series(1 / len(mem), index=mem)
            for k in mem:
                out[k] += v * share[k]
                used[k] = c
        rest = [k for k in members_s if k not in covered]
        if residual > 1e-9:
            w = weight[rest] if rest else pd.Series(dtype=float)
            if rest and w.sum() > 0:
                for k in rest:
                    out[k] += residual * w[k] / w.sum()
                    used[k] = f"{s_code} remainder"
            else:  # nowhere to put it: record, never drop silently
                losses[f"{s_code} unallocated remainder"] = residual
        elif residual < 0:
            losses[f"{s_code} remainder"] = residual
    return out, used, losses


def m2_foreign_owned(year: int, na: pd.DataFrame, prm: Params) -> tuple[list[dict], dict]:
    """Foreign owners' profit: FATS operating surplus of foreign-controlled firms, after
    depreciation, interest (non-financial firms) and corporate tax, times theta.

    Interest is deducted here because FATS/SBS operating surplus is before interest; interest
    paid to foreign lenders is counted once, in the BoP interest lines (m3), and intra-group
    interest to foreign parents in `fdi_debt_interest`.  Each FATS row carries `gross_base`,
    its FATS operating surplus before conversion, so the validator can check it against the
    published totals.
    """
    f = fats_foreign_gos(year, prm.consistent_scope)
    sec, codes = f["sections"], f["codes"]
    shares = section_country_shares(sec, f["col_totals"], f["cells"])
    published_cell = f["cells"].reindex(index=shares.index, columns=shares.columns).notna()
    tau = STATUTORY_CIT[year] if prm.tax == "statutory" else 0.0
    cr = corporate_ratios(year, prm.rho_basis)
    by_ind, used, losses = allocate_fats(sec.clip(lower=0), codes, na)
    diag = {
        "fats_scope": f["scope"],
        "fats_foreign_gos": float(by_ind.sum()),
        "fats_published_total": f["total"],
        "tau": tau,
        "theta": prm.theta,
        "interest_ratio_nonfin": cr["interest_nonfin"],
        "intra_group_share": cr["intra_group_share"],
        "foreign_gos_nonfin": by_ind[[k for k in by_ind.index if section(k) != "K"]],
        "fats_code": used,
        "cfc_ratio_nonfin": cr["cfc_nonfin"],
        "negative_sections": {**{k: float(v) for k, v in sec[sec < 0].items()}, **losses},
        "imputed_country_value": 0.0,
        "interest_deducted_nonfin": 0.0,
        "foreign_owned_nos": 0.0,  # before interest and tax, for Foreign Ownership Capture
    }
    rows = []
    for k, g_k in by_ind[by_ind > 0].items():
        s_code = section(k)
        fin = s_code == "K"
        keep = 1 - (cr["cfc_fin"] if fin else cr["cfc_nonfin"] + cr["interest_nonfin"])
        net = g_k * max(keep, 0.0) * (1 - tau) * prm.theta
        if not fin:
            diag["interest_deducted_nonfin"] += g_k * cr["interest_nonfin"] * cr["intra_group_share"]  # intra-group part only
        if s_code in set("BCDEFGHIJLMN"):  # Capture: non-financial sections B-N, covered by FATS in every year
            diag["foreign_owned_nos"] += g_k * (1 - cr["cfc_nonfin"]) * prm.theta
        for p, sh in shares.loc[s_code].items():
            if sh <= 0:
                continue
            imputed = p != "CONFIDENTIAL_PARTNERS" and not bool(published_cell.loc[s_code, p]) if p in published_cell.columns else p != "CONFIDENTIAL_PARTNERS"
            method = (
                f"FATS foreign-controlled GOS (code {used.get(k, '?')}) x(1 - {'CFC' if fin else 'CFC - interest'} "
                f"per euro of {'S12' if fin else 'S11'} GOS = {keep:.3f}) x(1-tau={tau}) x theta={prm.theta}; "
                f"UCI economy share of section {s_code}"
            )
            if imputed:
                # the section x country cell is suppressed: the country's published total is kept, but
                # its split across sections is fitted from published margins (IPF), not observed
                method += " [cell suppressed by Eurostat: split across sections fitted from published margins]"
                diag["imputed_country_value"] += net * sh
            else:
                if p != "CONFIDENTIAL_PARTNERS":
                    over = f["cells"].reindex(index=[s_code]).clip(lower=0).sum(axis=1).iloc[0] > sec.clip(lower=0).get(s_code, 0) * (1 + 1e-6)
                    method += " [published section x country cell, scaled down: published cells exceed the section total]" if over else " [published section x country cell]"
            r = _row("fdi_income", p, k, net * sh, "estimated", method, "Eurostat fats_activ / fats_g1a_08; nasa_10_nf_tr", "low" if (imputed or p == "CONFIDENTIAL_PARTNERS") else "medium")
            r["gross_base"] = g_k * sh
            r["fats_code"] = used.get(k, "")
            rows.append(r)
    if prm.bop_upper:
        fdi_nonfin = sum(r["value"] for r in rows if section(r["industry"]) != "K")
        bop = _bop(year, "S1V", "D4S__D__F5", "DEB")[0]
        if pd.notna(bop) and bop > fdi_nonfin > 0:
            scale = bop / fdi_nonfin
            for r in rows:
                if section(r["industry"]) != "K":
                    r["value"] *= scale
                    r["methodology"] += f" [SENSITIVITY bop_upper: scaled x{scale:.2f} to BoP FDI equity income paid by S1V]"
    if year < 2021 or prm.consistent_scope:  # finance outside FATS scope: foreign-owned banks via BoP
        b, how = _bop(year, "S122", "D4S__D__F5", "DEB")
        diag["bank_fdi_equity_bop"] = b
        if pd.notna(b) and b > 0:

            r = _row(
                "fdi_income",
                "CONFIDENTIAL_PARTNERS",
                "K64",
                b,
                "observed",
                f"BoP FDI equity income (dividends + reinvested earnings, after interest and tax) paid by deposit-taking corporations; partner not published by sector ({how})",
                "Eurostat bop_c6_a (sector10=S122)",
                "medium",
            )
            r["gross_base"] = float("nan")
            rows.append(r)
    return rows, diag


# ---------- M3 non-FDI investment income of non-SPE sectors ----------
@lru_cache(maxsize=None)
def _bop_c6() -> pd.DataFrame:
    fs = [f for f in glob.glob(str(EUROSTAT / "bop_c6_a__*.parquet"))]
    d = pd.concat([pd.read_parquet(f) for f in fs], ignore_index=True).drop_duplicates()
    d["TIME_PERIOD"] = d.TIME_PERIOD.astype(int)
    return d


def _bop_raw(year: int, sector: str, item: str, flow: str) -> float:
    d = _bop_c6()
    x = d[(d.sector10 == sector) & (d.sectpart == "S1") & (d.bop_item == item) & (d.stk_flow == flow) & (d.partner == "WRL_REST") & (d.TIME_PERIOD == year)]
    v = x["OBS_VALUE"].dropna()
    return float(v.iloc[0]) if len(v) else float("nan")


def _bop(year: int, sector: str, item: str, flow: str) -> tuple[float, str]:
    """BoP value by resident sector; NaN (never 0) when confidential or unpublished.

    S1V (firms and households) is derived as S1P - S12M when suppressed but both are published.
    """
    v = _bop_raw(year, sector, item, flow)
    if pd.notna(v):
        return v, "published"
    if sector == "S1V":
        a, b = _bop_raw(year, "S1P", item, flow), _bop_raw(year, "S12M", item, flow)
        if pd.notna(a) and pd.notna(b):
            return a - b, "derived as S1P - S12M"
    return float("nan"), "confidential or unpublished"


NON_FDI_ITEMS = {
    "D41__O__FLA": "other_investment_income",  # interest on loans and deposits
    "D41__P__F3": "portfolio_income",  # interest on debt securities
    "D42__P__F51": "portfolio_income",  # dividends on portfolio equity
    "D44P__O__F6": "other_investment_income",  # investment income attributable to policyholders
}
# The BoP by resident sector is published for the world only (no EU27 / extra-EU split for these
# items), so these flows go to WORLD_UNALLOCATED.


def m3_other(year: int, na: pd.DataFrame, prm: Params, intra_group_cap: float = float("inf"), foreign_gos: pd.Series | None = None) -> tuple[list[dict], dict]:
    """Non-FDI investment income of non-SPE sectors, plus intra-group interest.

    `intra_group_cap` = intra-group share x interest deducted from foreign-controlled firms'
    surplus in m2: only that part goes to foreign parents; the rest of the deducted interest went
    to Cypriot lenders (retained) or to foreign third-party lenders (already in the S1V lines).
    Intra-group interest is allocated in proportion to foreign-controlled surplus
    (`foreign_gos`), the base it was computed from.  Other interest paid by firms and households
    is split between firms (industries by GOS, excluding imputed rent) and households (mortgage
    interest, booked to imputed rent L68A) using their shares of D41 paid.
    """
    rows, diag = [], {"confidential_items": {}}
    nonfin = na.drop(index=[k for k in na.index if section(k) in {"K", "O"}])
    firm_w = nonfin["B2A3G"].drop(index=["L68A", "T"], errors="ignore")
    hh_share = corporate_ratios(year)["household_interest_share"]

    def allocation(mech: str, item: str = "D41__O__FLA") -> pd.Series:
        if mech == "fdi_debt_interest" and foreign_gos is not None and foreign_gos.clip(lower=0).sum() > 0:
            return _alloc(1.0, foreign_gos)
        if item != "D41__O__FLA":  # securities interest, portfolio dividends, policyholder income: firms only
            return _alloc(1.0, firm_w)
        firms = _alloc(1.0 - hh_share, firm_w)
        return pd.concat([firms, pd.Series({"L68A": hh_share})])

    def add_s1v(item: str, mech: str, label: str, cap: float = float("inf")):
        v, how = _bop(year, "S1V", item, "DEB")
        if pd.isna(v):
            diag["confidential_items"][f"S1V {item}"] = how
            # upper bound: S1V total investment income paid minus its published components
            tot, _ = _bop(year, "S1V", "D4P__F", "DEB")
            comps = [c for c in ("D4S__D__F5", "D41__D__FLA", "D41__O__FLA", "D41__P__F3", "D44P__O__F6", "D42__P__F51", "D443__P__F52") if c != item]
            known = sum(v for v in (_bop(year, "S1V", c, "DEB")[0] for c in comps) if pd.notna(v))
            diag.setdefault("confidential_upper_bound", {})[f"S1V {item}"] = max(tot - known, 0.0) if pd.notna(tot) else float("nan")
            return
        if v <= 0:
            return
        if v > cap:
            diag["intra_group_interest_bop"] = v
            label += f"; capped at the intra-group share of interest deducted from foreign-controlled firms ({cap:.0f} of BoP {v:.0f})"
            v = cap
        key = "foreign-controlled surplus" if mech == "fdi_debt_interest" else (f"firms by GOS, households {hh_share:.0%} to imputed rent (mortgage interest)" if item == "D41__O__FLA" else "firms by GOS")
        for k, x in (v * allocation(mech, item)).items():
            if x > 0:
                rows.append(_row(mech, "WORLD_UNALLOCATED", k, x, "estimated", f"BoP {item} paid by firms and households (S1V, {how}); {label}; allocated: {key}", "Eurostat bop_c6_a; nasa_10_nf_tr", "low"))

    for item, mech in NON_FDI_ITEMS.items():
        add_s1v(item, mech, "counted once: FATS profit is after interest")
    # intra-group interest to foreign parents (FDI debt): removed from FATS profit by the interest
    # deduction, so it is booked here from the BoP
    add_s1v("D41__D__FLA", "fdi_debt_interest", "FDI debt interest (intra-group)", cap=intra_group_cap)

    # S122: deposit-taking banks.  Central: net of receipts (intermediation); sensitivity: gross.
    paid = {i: _bop(year, "S122", i, "DEB")[0] for i in NON_FDI_ITEMS}
    recv = {i: _bop(year, "S122", i, "CRE")[0] for i in NON_FDI_ITEMS}
    for flow, vals in (("paid", paid), ("received", recv)):
        for i, v in vals.items():
            if pd.isna(v):
                diag["confidential_items"][f"S122 {i} {flow}"] = "confidential or unpublished (omitted from the bank net)"
    gross_paid = sum(v for v in paid.values() if pd.notna(v))
    net = gross_paid - sum(v for v in recv.values() if pd.notna(v))
    diag.update(banks_interest_paid=gross_paid, banks_interest_received=gross_paid - net, banks_net_non_fdi=net)
    if prm.banks_gross and gross_paid > 0:
        # SENSITIVITY: interest on non-resident deposits funds domestic lending, so it is a claim
        # on the borrowers' surplus (firms and households), not on the banks' own surplus
        for k, x in (gross_paid * allocation("other_investment_income")).items():
            if x > 0:
                rows.append(_row("other_investment_income", "WORLD_UNALLOCATED", k, x, "estimated", "SENSITIVITY: banks' non-FDI investment income paid abroad, gross, charged to borrowers", "Eurostat bop_c6_a", "low"))
    elif net > 0:
        rows.append(_row("other_investment_income", "WORLD_UNALLOCATED", "K64", net, "estimated", "BoP non-FDI investment income of S122, paid minus received", "Eurostat bop_c6_a", "low"))
    # S13: general government -> financed from the tax pool
    for item in ("D41__O__FLA", "D41__P__F3"):
        v, how = _bop(year, "S13", item, "DEB")
        if pd.isna(v):
            diag["confidential_items"][f"S13 {item}"] = how
        elif v > 0:
            rows.append(_row("public_debt_interest", "WORLD_UNALLOCATED", PRODUCT_TAXES, v, "observed", f"BoP {item} ({'interest on loans and deposits' if item.startswith('D41__O') else 'interest on debt securities'}) paid by general government; financed from taxes (attribution convention); counterpart country not published by sector", "Eurostat bop_c6_a", "high"))
    # S12M: other financial corporations (SPE-dominated) - reported, excluded unless requested
    ofc, _ = _bop(year, "S12M", "D4P__F", "DEB")
    diag["ofc_investment_income_paid"] = ofc
    if prm.include_ofc and pd.notna(ofc) and ofc > 0:
        rows.append(_row("portfolio_income", "WORLD_UNALLOCATED", "K66", min(ofc, na.loc["K66", "B2A3G"]), "estimated", f"SENSITIVITY: S12M investment income paid, capped at K66 GOS (uncapped {ofc:.0f})", "Eurostat bop_c6_a", "low"))
    return rows, diag


# ---------- M4 taxes to EU institutions ----------
def m4_eu_taxes(year: int) -> list[dict]:
    v = _sector().loc[(year, "S2"), "D2REC"]
    if pd.isna(v) or v <= 0:
        return []
    return [
        _row(
            "taxes_to_eu_institutions",
            "EU_INST",
            PRODUCT_TAXES,
            v,
            "observed",
            "Taxes on production and imports received by the rest of the world (EU own resources)",
            "CYSTAT 0630030E",
            "high",
        )
    ]


def product_taxes(year: int, na: pd.DataFrame) -> float:
    return gdp(year) - float(na["B1G"].sum())


@lru_cache(maxsize=1)
def calibrated_theta() -> float:
    from .ownership_data import theta_central

    return round(theta_central(), 3)


def build_account(year: int, prm: Params = Params()) -> tuple[IncomeAccount, dict]:
    if prm.theta is None:
        prm = replace(prm, theta=calibrated_theta())
    na = na_industry(year)
    rows, d1 = m1_labour(year, na)
    r2, d2 = m2_foreign_owned(year, na, prm)
    r3, d3 = m3_other(year, na, prm, intra_group_cap=d2["interest_deducted_nonfin"], foreign_gos=d2["foreign_gos_nonfin"])
    rows += r2 + r3 + m4_eu_taxes(year)
    out = pd.DataFrame(rows)
    if "gross_base" not in out:
        out["gross_base"] = float("nan")
    if "fats_code" not in out:
        out["fats_code"] = ""
    out = out.groupby(["mechanism", "partner", "industry"], as_index=False).agg(
        value=("value", "sum"),
        status=("status", "first"),
        methodology=("methodology", "first"),
        source=("source", "first"),
        confidence_level=("confidence_level", "first"),
        gross_base=("gross_base", lambda x: x.sum(min_count=1)),
        fats_code=("fats_code", "first"),
    )
    diag = {**d1, **d2, **d3, "capped": {}}
    # Capital-income mechanisms are bounded by each industry's GOS; public interest by the tax pool.
    cap_mech = out.mechanism.isin(
        ["fdi_income", "fdi_debt_interest", "portfolio_income", "other_investment_income"]
    )
    drawn = out[cap_mech].groupby("industry")["value"].sum()
    over = (drawn - na["B2A3G"].reindex(drawn.index)).clip(lower=0)
    for k, ex in over[(over > 1e-9) & (drawn > 0)].items():
        m = cap_mech & (out.industry == k)
        scale = max(na.loc[k, "B2A3G"], 0.0) / out.loc[m, "value"].sum()
        out.loc[m, "value"] *= scale
        out.loc[m, "methodology"] += f" [scaled x{scale:.3f}: capped at industry GOS]"
        out.loc[m, "status"] = "estimated"  # capping is a modelling step, never an observation
        diag["capped"][k] = float(ex)
    out = out[out["value"] > 0].reset_index(drop=True)
    acc = IncomeAccount(
        country="CY",
        year=year,
        gva=na["B1G"],
        coe=na["D1"],
        other_taxes=na["D29X39"],
        gos=na["B2A3G"],
        product_taxes=product_taxes(year, na),
        outflows=out,
    )
    diag["gdp"] = acc.gdp
    diag["official_primary_income_paid"] = float(
        sum(_sector().loc[(year, "S2"), c] for c in ("D1REC", "D4REC", "D2REC"))
    )
    diag["official_gni"] = float(_sector().loc[(year, "S1"), "B5G"])
    return acc, diag
